### ISSUE TITLE
For info, here is a similar tool

### ISSUE THREAD

**Issue by woctezuma** [rom1504/img2dataset#1]
Hello Romain,

For info, here is a tool called `imagedownloader` which I have in my starred repositories: https://github.com/alcinos/imagedownloader
It is a fork by a Facebook guy which implements **(*)**. The original tool can be installed with:

```bash
%pip install imgdl
```

As far as I understand, this tools serves a similar purpose to `img2dataset`, with a few differences:
- there is no subfolder,
- filenames are either hashed, or determined by a user-defined function **(*)**,
- persistent cache,
- etc.

Is there any advantage to switch from `imagedownloader` to `img2dataset`?

**Comment by rom1504** [comment]
hi,
yes resizing, subfolders, number indexed files, and being maintained.
but more importantly what I listed in the roadmap here https://github.com/rom1504/img2dataset#road-map
the goal of this repo is to turn a list of url in an usable dataset, not only to download the files

**Comment by woctezuma** [comment]
Thank you for the answer! :)

**Comment by woctezuma** [comment]
I saw your message in https://github.com/felipeam86/imagedownloader/issues/1

Good job for all the work! I will try your tool next time I need to download lots of images!
