### ISSUE TITLE
clip-retrieval-getting-started.ipynb giving errors (Urgent)

### ISSUE THREAD

**Issue by minakshimathpal** [rom1504/img2dataset#141]
![image](https://user-images.githubusercontent.com/61991627/154071809-1053d665-20ec-4724-a01d-9bb84533601f.png)
Hello there I am new to the world of deep learning.I am trying to run clip-retrieval-getting-started.ipynb but getting the error attached as snip....Please help its urgent

**Comment by minakshimathpal** [comment]
![image](https://user-images.githubusercontent.com/61991627/154159122-c3edfff0-25e7-4240-8d80-7b7685d92b9b.png)
Thanks a lot for replying

**Comment by minakshimathpal** [comment]
@rom1504  I am trying to replicate "clip-retrieval-getting-started.ipynb" as is

**Comment by rom1504** [comment]
Can you try to update your pip version then update albumentation?
It seems you installed an old version

**Comment by minakshimathpal** [comment]
@rom1504  you are a gem..thank you. It worked

**Comment by minakshimathpal** [comment]
@rom1504 Is there any way to use my own dataset which has no urls just the images

**Comment by rom1504** [comment]
yes you can use clip inference on images  files (files input format)

**Comment by rom1504** [comment]
please open an issue in clip-retrieval if still needed
