### ISSUE TITLE
support uploading shards directly to cloud storage

### ISSUE THREAD

**Issue by GallagherCommaJack** [rom1504/img2dataset#146]
would be nice for downloads of large datasets (eg LAION) to not need to have enough local storage to hold the whole dataset, and it shouldn't be too hard to use [smart_open](https://pypi.org/project/smart-open/) or [fsspec](https://pypi.org/project/fsspec/) to replace the output directory with an output bucket.

**Comment by rom1504** [comment]
Yes and you're in luck, this is already supported, see https://github.com/rom1504/img2dataset#file-system-support

**Comment by rom1504** [comment]
You may also be interested by https://github.com/rom1504/img2dataset/blob/main/examples/distributed_img2dataset_tutorial.md if you want to use multiple nodes to download

I used this setup to download our new dataset (soon to be announced) laion5B

**Comment by GallagherCommaJack** [comment]
oh! great :)
