### ISSUE TITLE
How to download image and text only

### ISSUE THREAD

**Issue by thunanguyen** [rom1504/img2dataset#151]
Hi, my desktop PC does not have large storage and that is why I want to download images and texts only, remove other unnecessary stat and parquet files to save disk space. Is this OK and is this possible?

**Comment by rom1504** [comment]
hi,
This will save about 1% of the storage. Is it really worth it to lose that information for 1% ?
to save space, I'd recommend instead to resize at a lower dimension

**Comment by thuangb** [comment]
> hi, This will save about 1% of the storage. Is it really worth it to lose that information for 1% ? to save space, I'd recommend instead to resize at a lower dimension

Thank you for your reply, I would consider that. I have only 1TB so do you think resize LAION400M to 64 x 64 is enough

**Comment by rom1504** [comment]
yes indeed it will take less than 1TB in 64x64

however it might make more sense to download only a parts of the images in higher resolution

what is your use case?

**Comment by thuangb** [comment]
Currently, I'm doing some experiments about training a variant DALL-E. What I focus is zero-shot generation capability of the model so image quality is not a high priority. That is why a large dataset but low resolution is acceptable for me
