### ISSUE TITLE
option to resume a partially completed download

### ISSUE THREAD

**Issue by dashstander** [rom1504/img2dataset#155]
Honestly could be as simple as checking whether a file already exists locally before trying to download it. Would it be alright if made a PR to that effect?

This brought to you by: I'm going to need my internet for a zoom call tomorrow morning and don't want to restart my download from the beginning 😅

**Comment by rom1504** [comment]
hey,
I described a potential solution at https://github.com/rom1504/img2dataset/issues/6#issuecomment-1033767915
I'm busy with other things right now, but if you want to give it a try feel free.
I'm warning you however, it's not that easy.

**Comment by rom1504** [comment]
This is now done, see https://github.com/rom1504/img2dataset#incremental-mode
