### ISSUE TITLE
Skipped shard numberings

### ISSUE THREAD

**Issue by xiankgx** [rom1504/img2dataset#174]
Hi, I used img2dataset to download a custom image-text dataset. It completed without issues. However, I'm faced with gaps in the shard numberings. I'm observing training terminated because of some files not found. Of course, I could easily just duplicate another shard to this missing shard file as an easy fix.

**Comment by rom1504** [comment]
hello,
you have 2 choices
1. use a warn and continue helper in webdataset to avoid errors in your data loader, eg https://github.com/rom1504/laion-prepro/blob/main/laion5B/usage_guide/dataloader_pytorch.py#L16
2. use a recent version of img2dataset that allow you to rerun the download with the same input and the same output folder to complete the missing shards

**Comment by xiankgx** [comment]
Ok, I'll try the handlers in webdataset. The dataset was download only recently, 2 days ago. The img2dataset was installed through pip.

**Comment by rom1504** [comment]
Yes i mean if you rerun img2dataset it will get missing shards
