### ISSUE TITLE
type object 'SparkSession' has no attribute 'getActiveSession'

### ISSUE THREAD

**Issue by viyjy** [rom1504/img2dataset#175]
Hi,

Thanks for your awesome work.
I am using AWS EMR (with spark) to download the LAION5B dataset by following this [distributed mode](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion5B.md).
However, when I run the download.py in the EMR's notebook, I got this error:
```
An error was encountered:
type object 'SparkSession' has no attribute 'getActiveSession'
Traceback (most recent call last):
  File "python3.7/site-packages/img2dataset/main.py", line 169, in download
    max_shard_retry,
  File "python3.7/site-packages/img2dataset/distributor.py", line 62, in pyspark_distributor
    spark = SparkSession.getActiveSession()
AttributeError: type object 'SparkSession' has no attribute 'getActiveSession'
```
Any suggestions? Thanks.

Best

**Comment by rom1504** [comment]
Hi, it seems like you are using an older version of spark
Can you update it ?

**Comment by viyjy** [comment]
Hi, I have upgraded the spark to the latest version, but it still doesn't work.
I am using EMR notebook, it might be different from your tutorial? Thanks.
