### ISSUE TITLE
Error when using simple_example.py

### ISSUE THREAD

**Issue by YUHANG-Ma** [rom1504/img2dataset#176]
Hi, thanks for your contribution of the code.
When I try to use img2dataset to convert the file I downloaded from https://huggingface.co/datasets/laion/laion2B-en/tree/main
 to webdataset, I met the issue shown in the figure below.
![71c87a663d83a201dac426e4b5bdd37](https://user-images.githubusercontent.com/72591225/173330299-a3d566c5-15ad-458d-9f31-8a675b29fd20.png)
And this is my code. I just download one parquet from https://huggingface.co/datasets/laion/laion2B-en/tree/main. 
![image](https://user-images.githubusercontent.com/72591225/173330553-b47fdd26-0f9f-40d5-95c4-4f11dedacd6f.png)
Could I ask what the problem is?

**Comment by rom1504** [comment]
Did you figure it out ?

**Comment by ryx19th** [comment]
The same issue here
