### ISSUE TITLE
viability of downloading LAION-5b on a single node 

### ISSUE THREAD

**Issue by mitchypi** [rom1504/img2dataset#189]
Hi, I'm trying to download the LAION-5b dataset for training, and I was wondering if it would be viable to run img2dataset to download it without a pyspark cluster if I were to skip resizing. Basically, is there any purpose to having a pyspark cluster other than to handle resizing of all the images. From what I can see the bottlenecks without resizing would simply be download and write speed. Thanks in advance !

**Comment by rom1504** [comment]
Hello, the bottlenecks are
* storage: you need 500TB to download without resizing
* bandwidth: you need 6Gbps to download in a week
* cpu: indeed very low if you use disable_all_reencoding option

**Comment by mitchypi** [comment]
Thank you!
