### ISSUE TITLE
Cannot download from subset of LAION-5B

### ISSUE THREAD

**Issue by dogoulis** [rom1504/img2dataset#195]
I have created a .txt file with the URLs taken from the cheescake class on the LAION-5B database. 
I run the command img2dataset --url_list=subset.txt --output_folder=out and it produces the following error:

CSV parse error: Expected 1 columns, got 2: https://img1.baidu.com/it/u=1798831392,1750834138&fm=15&fmt=auto&gp=0.jpg

**Comment by rom1504** [comment]
Hi, you're hitting https://github.com/rom1504/img2dataset/issues/196 
In the mean time I advise you use a better format than txt. 
For example the laion5B search demo provides you json files if you click on the download button

**Comment by dogoulis** [comment]
It worked with the .json file provided.  Thanks!

**Comment by rom1504** [comment]
closing in favor of https://github.com/rom1504/img2dataset/issues/196
