### ISSUE TITLE
Is there a way to only download image with specific resolution?

### ISSUE THREAD

**Issue by Penguin-jpg** [rom1504/img2dataset#203]
Hello! If I only want images with resolution greater or equal than 512x512, is there a way to do it?

**Comment by rom1504** [comment]
yes, https://github.com/rom1504/img2dataset#filtering-the-dataset

however I advise you to instead pre filter the dataset if your metadata has the resolution (for example laion5B does, and you can filter it with a script like https://github.com/rom1504/laion-prepro/blob/main/laion5B/high_resolution/high_resolution.py )

**Comment by Penguin-jpg** [comment]
> yes, https://github.com/rom1504/img2dataset#filtering-the-dataset
> 
> however I advise you to instead pre filter the dataset if your metadata has the resolution (for example laion5B does, and you can filter it with a script like https://github.com/rom1504/laion-prepro/blob/main/laion5B/high_resolution/high_resolution.py )

Thanks for reply. It helps a lot!
