### ISSUE TITLE
How to download SBUcaptions and Visual Genome (VG) dataset in webdataset format

### ISSUE THREAD

**Issue by sanyalsunny111** [rom1504/img2dataset#205]
For Vision and Language pretraining cc3m, mscoco, SBUcaptions and VG are very relevant datasets. I haven't been able to download SBU captions and VG. Here are my questions.

1) How to download SBU captions and VG's metadata?
2) How to download these datasets on webdataset format?

Could you also please provide me with a tutorial or just some hints to download it in webdataset format using img2dataset? Thank you in advance.

**Comment by rom1504** [comment]
https://www.cs.rice.edu/~vo9/sbucaptions/ sbu captions is provided as url + captions in json. You can use that as input of img2dataset

**Comment by rom1504** [comment]
https://visualgenome.org/api/v0/api_home.html visual genome is not distributed as image urls, so you can simply download the images and make a tar with them. That's what webdataset is.

**Comment by sanyalsunny111** [comment]
@rom1504 Could you, please add some comments on how to download SBUcaptions and VG using img2dataset?

**Comment by sanyalsunny111** [comment]
This is the way to download SBU captions @rom1504  please also add this to your example file.
`wget https://www.cs.rice.edu/~vo9/sbucaptions/sbu-captions-all.tar.gz`

`tar -xvzf sbu-captions-all.tar.gz`

`img2dataset --url_list sbu-captions-all.json --input_format "json" --url_col "image_urls" --caption_col "captions" --output_format webdataset --output_folder sbucaptions --processes_count 16 --thread_count 64 --image_size 256`

**Comment by rom1504** [comment]
if you can open a PR to add an example in the dataset folder, it would be great

**Comment by sanyalsunny111** [comment]
Sure doing it right away. @rom1504  Could you please let me know how to down VG images and captions as webdataset?

**Comment by rom1504** [comment]
sbu-captions is done

VG images can be converted using tar directly
