### ISSUE TITLE
Convert dataset already on disk to webdataset

### ISSUE THREAD

**Issue by AlaaKhaddaj** [rom1504/img2dataset#211]
Hello, 

I have a dataset that already is in ImageFolder format. Can I use this code to convert it to a webdataset?

**Comment by rom1504** [comment]
No but there is an easy way to do this.
tar cf 0.tar your_folder/

You may create several such tars if you have many images

**Comment by AlaaKhaddaj** [comment]
I see, thanks!

Also, if I have a custom dataset object with __len__ and __getitem__, do you know how I can save it as a webdataset?

**Comment by rom1504** [comment]
you can use tarwriter from webdataset
