### ISSUE TITLE
fresh install on amazon linux 2 - dependencies problems

### ISSUE THREAD

**Issue by rvencu** [rom1504/img2dataset#215]
Installing img2dataset on al2 I noticed

s3fs is not declared as dependency

when installing s3fs I get this warning
`ERROR: img2dataset 1.33.0 has requirement fsspec==2022.1.0, but you'll have fsspec 2022.10.0 which is incompatible.`

**Comment by rom1504** [comment]
you need s3fs==2022.1.0

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/blob/main/Makefile#L19

you may also directly use the pex like this:
```
wget https://github.com/rom1504/img2dataset/releases/download/1.33.0/img2dataset.pex
chmod +x img2dataset.pex
./img2dataset.pex
```

**Comment by rvencu** [comment]
OK, it works despite the warning, though. thank you
