### ISSUE TITLE
Distributed downloading with known `num_workers`, `worker_id` and `master_ip`

### ISSUE THREAD

**Issue by YANG-H** [rom1504/img2dataset#222]
Hi, 
I'm using `img2dataset` on a cluster where `num_workers`, `worker_id` and `master_ip` are already known. Is it possible to pass these to the cli as arguments or environment variables?

**Comment by rom1504** [comment]
see https://github.com/rom1504/img2dataset/blob/main/examples/pyspark_example.py to specify you own spark session
