### ISSUE TITLE
Question about number of LAION-Aesthetic samples

### ISSUE THREAD

**Issue by dxli94** [rom1504/img2dataset#225]
Hi Romain,

Thanks for the tool. It is amazing.

I see https://github.com/LAION-AI/laion-datasets/blob/main/laion-aesthetic.md mentions "use laion-aesthetic which contains **120M** aesthetic samples (**score > 7**)". Among them, the english version has 51M.

There is also "625K image-text pairs with predicted aesthetics scores of 6.5 or higher" on https://laion.ai/blog/laion-aesthetics/, also from "subsets of the LAION 5B samples with English captions".

It is a bit confusing since 51M >> 625K, despite the 51M one has an even higher score threshold.

I wonder what do I miss here and what is the difference between these two versions of laion-aesthetic?

Thanks for your time and efforts. Your response is appreciated.

Best
Dongxu

**Comment by rom1504** [comment]
Hi, the one mentioned in the example here is aesthetic V1 while the second
one you mention is V2. Details are explained in that blogpost

**Comment by dxli94** [comment]
That's clear. Thanks for the clarification.

Best
