### ISSUE TITLE
Error when using "/img2dataset.pex"

### ISSUE THREAD

**Issue by SCZwangxiao** [rom1504/img2dataset#232]
I followed the procedures in [Distributed img2dataset tutorial](https://github.com/rom1504/img2dataset/blob/main/examples/distributed_img2dataset_tutorial.md#distributed-img2dataset-tutorial). However, when runing ``./img2dataset.pex download.py``, I got an error:
```bash
File "./img2dataset.pex", line 2
SyntaxError: Non-UTF-8 code starting with '\xc3' in file ./img2dataset.pex on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by rom1504** [comment]
you can re-generate it for your environment with make build-pex if needed
