### ISSUE TITLE
Failed to download all of CC12M

### ISSUE THREAD

**Issue by AlaaKhaddaj** [rom1504/img2dataset#242]
I have been trying to download CC12M, using the same instructions you provided, however, the download is not complete.

I am getting the following error for a significant number of iterations:

`total   - success: 0.792 - failed to download: 0.195 - failed to resize: 0.013 - images per sec: 485 - count: 12423374`
 
After the code is done, I end up with 1243 tar files. How can I solve this to get the full CC12M dataset?

**Comment by rom1504** [comment]
Hey, did you set up knot resolver for DNS resolving?
This is really important to avoid overloading your DNS and hence having a
low success rate

**Comment by Reveyer** [comment]
@rom1504 Hi, is there any way to re-download only the failed data?

**Comment by learnerynwei** [comment]
+1  is there method?

**Comment by rom1504** [comment]
You can read the output parquet files and select only the samples that are
failed status, write that as parquet (you can do that with pandas or spark)
Then rerun img2dataset on it
