### ISSUE TITLE
Respect x-robots-directives by default

### ISSUE THREAD

**Issue by Stealcase** [rom1504/img2dataset#245]
# The Problem:
Currently the default behaviour of img2dataset is to ignore x-robots-tag and robots.txt directives.

It does not honor "nofollow" and "noindex", nor "noai" and "noimageai".

This goes against the Terms of Use for Common Crawl, the dataset that all LAION datasets are based on, and one of the most popular datasets used with this tool.
https://commoncrawl.org/terms-of-use/

Common Crawl does not care for directives like "noai" and "noimageai", because they do not have any knowledge that the data they index will be used for AI purposes. img2dataset does not have this excuse.. This tool is used mainly for Machine Learning. 

There was a suggestion to implement this 3 weeks ago, but the ultimate decision was to keep the default of ignoring "x-robots-tag". 
https://github.com/rom1504/img2dataset/pull/218

This is an antipattern, and can in certain cases involve breaking the law. 
Users of img2dataset typically don't want to break the law or Terms of Use unintentionally and without knowledge. 

This should be rectified.
The time between a dataset is created and an image is downloaded can result in changes on the web: it is not enough to rely on LAION to filter "noai" tags. 

## The Sollution: 
* Respect x-robots-tag by default.

**Comment by suleyth** [comment]
It should have been this way from the very beginning. This can have the potential to cut from its roots a lot of the damage AI art has done already. There is literally no reason to not do it.

**Comment by Kerenas** [comment]
I find it rather interesting that the developer behind this has made the conscious decision beforehand to actually actively ignore "x-robots-tag." I feel like this shows a conscious disregard not only for the ethics of AI and webcrawlers, but for the law itself. I have no doubt that this database going and downloading every image it sees ever with no regard as to whether the person behind that image WANTS it used  by this database certainly opens this project up to some manner of liability.

While the websites certainly are protected from it in some manner of arbitration, nothing is stopping artists in the community from targeting this developer en masse with Cease and Desist, much less lawsuits. I would certainly argue that with the way this is being used and developed that the developer behind this is absolutely liable for any copyright infringement. And could very easily be sued for any number of things being that this utility actively ignores protections put in place against it.

I would tell you, rom1504, that if you don't want to think of that possibility of being sued that you start to at the very minimum heed and manner of x-robots-tag. If an artist does not want their art used by AI or in an AI database, it should not be there, nor does it belong there.

**Comment by rom1504** [comment]
Can you please go trolling in reddit ?
Thanks

I will think about this problem, there is no need to try and threaten me.

**Comment by rom1504** [comment]
As a reminder, it is already possible for any user to filter out images with these tags, as documented there https://github.com/rom1504/img2dataset#respecting-opt-out-directives
and also there https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-art-noai.md

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/pull/249 opting out is now enabled by default

If using this default, be aware there are ethical issues with slowing down democratization of skills and art to millions of people.
