### ISSUE TITLE
Does an 'noai' opt-out directive even work?

### ISSUE THREAD

**Issue by milotheirself** [rom1504/img2dataset#247]
Related to #245.

@rom1504, what was the source of the opt-out directive? Who suggested that?

Even though I try to stay neutral on AI issues – I have to agree with @Stealcase that assuming that the entire web is willing or even able to adopt these opt-out directives is the same as doing nothing about the copyright concerns behind them at all.

And this project shows even less concern by making this filter for an explicit opt-out optional, why?

**Comment by rom1504** [comment]
That's a good point! Removing that feature is a good idea, please open a PR.

**Comment by milotheirself** [comment]
Can you answer the question first. Who suggested the opt-out directive? :/

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/pull/218 deviant art

**Comment by rom1504** [comment]
I think I will start adding information in the readme like https://gizmodo.com/moma-art-museum-ai-ai-art-generator-refik-anadol-1849800994 to take into account the concerns of the AI art community

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/pull/249 opting out is now enabled by default

If using this default, be aware there are ethical issues with slowing down democratization of skills and art to millions of people.
