### ISSUE TITLE
Add information in the readme to promote the rights of AI artists and AI trainers

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#250]

**Comment by Stealcase** [comment]
I think this is a good idea, as it's very useful for artists to know their rights, especially in a commercial sense. 

If you find any legal resources that handles the topic of Machine Generated images, it's probably a good idea to include links to it. This will probably be a hot topic the coming years with a lot of developments as lawsuits and cases are settled and the courts  reach potentially contradictory decisions.

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/pull/249 done

**Comment by rom1504** [comment]
https://github.com/rom1504/img2dataset/pull/249 done

**Comment by Kerenas** [comment]
> I think this is a good idea, as it's very useful for artists to know their rights, especially in a commercial sense.
> 
> If you find any legal resources that handles the topic of Machine Generated images, it's probably a good idea to include links to it. This will probably be a hot topic the coming years with a lot of developments as lawsuits and cases are settled and the courts reach potentially contradictory decisions.

Here is a small index of Case Law involving Artificial Intelligence and Machine Learning. While there is little to no case law involving AI Art in specific, I feel like these cases can help to act as a sort of guideline. In the case of me finding any AI Art Case Law, I will likely email this to rom, as this specific application of machine learning is fairly young, and any and all guidelines to follow will be extremely useful in aiding the growth of the software.

https://businesslawtoday.org/2021/06/recent-developments-in-artificial-intelligence-cases/

While none of the cases listed here appear to treat any manner of AI or ML algorithm as alive, nor should they, they do thoroughly seem to believe that an AI should not be infringing on the rights and liberties of others. I do hope that this is helpful for the future of this project.
