### ISSUE TITLE
When use parquet as output format decode the bytes in jpg, the image result color seems wrong. 

### ISSUE THREAD

**Issue by svjack** [rom1504/img2dataset#282]
When I use  parquet as output format , I read the parquet file by pyarrow,
The color seems changed after decode,
Following is my code snip:

```python
import pyarrow.parquet as pq
import numpy as np
import cv2
from PIL import Image

def jpg_val_to_img(jpg_bytes):
    img_buf = np.frombuffer(jpg_bytes, np.uint8)
    img = cv2.imdecode(img_buf, cv2.IMREAD_UNCHANGED)
    img = Image.fromarray(img)
    return img

table0 = pq.read_table("00000.parquet")
df0 = table0.to_pandas()

jpg_val_to_img(df0["jpg"].iloc[0])
```

The original image is:
![cupola2](https://user-images.githubusercontent.com/27874014/223311438-9ab17cc9-024d-46c8-bb5f-f3ead5c881ba.jpg)

The image decode is:
![img0](https://user-images.githubusercontent.com/27874014/223311571-952a6e07-421d-4ca7-bbea-5a43a37191c9.png)

**Comment by rom1504** [comment]
See https://stackoverflow.com/a/43234001

OpenCV and PIL do not use the same color scheme
