### ISSUE TITLE
Respect robots.txt

### ISSUE THREAD

**Issue by slavakurilyak** [rom1504/img2dataset#284]
It would be great to see opt-out directives for robots.txt. This "[should probably be implemented in a way that allows caching to improve performance, and avoid multiple calls to "/robots.txt" per website](https://github.com/rom1504/img2dataset/pull/249#:~:text=should%20probably%20be%20implemented%20in%20a%20way%20that%20allows%20caching%20to%20improve%20performance%2C%20and%20avoid%20multiple%20calls%20to%20%22/robots.txt%22%20per%20website)", as suggested by @Stealcase.

**Comment by rom1504** [comment]
Yes let's continue the discussion there https://github.com/rom1504/img2dataset/issues/48
