### ISSUE TITLE
Fix README regarding lossless webp

### ISSUE THREAD

**Issue by jonasricker** [rom1504/img2dataset#288]
In the README it says 

> webp at quality 100 is lossless

However, I noticed that with `--encode_quality 100`, images are smaller than expected. According to the [OpenCV Docs](https://docs.opencv.org/3.4/d8/d6a/group__imgcodecs__flags.html), lossless compression is only used if `IMWRITE_WEBP_QUALITY ` is **above** 100. I verified that using `--encode_quality 101` generates images with larger file size.

The README should probably be updated to make users aware of this subtle difference.

**Comment by rom1504** [comment]
interesting!

could you PR that please ?
