### ISSUE TITLE
Make it scale to 1B pictures

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#29]
* [x] further optimization on the resizing part #8 
* [x] better multi node support #20 
* [x] run it

**Comment by rom1504** [comment]
so I discussed with other users of this tool, and the conclusion is that the cpu usage of resizing is the main bottleneck : if you have N times more cpu, it goes N times faster
I am currently using only 100MB/s of bandwidth and 30MB/s of disk, so it could be possible to go like 8x faster on this one machine.
Conclusion, having very optimized resizing is crucial to make this faster.
Going 8x faster could make it possible to do 1B in 25h.

Ideas:
* use opencv gpu resizing
* try pillow-simd

Setting up a good benchmark for resizing should make it easy to measure and improve this

**Comment by rom1504** [comment]
It seems decoding and encoding takes a large part of the processing time.
Try https://pypi.org/project/simplejpeg/

**Comment by rom1504** [comment]
https://github.com/loopbio/PyTurbojpeg/tree/loopbio http://blog.loopbio.com/video-io-2-jpeg-decoding.html

**Comment by rom1504** [comment]
almost done, will confirm soon with a run to download laion2B-english (then same for 2B-multi and 1B-nolang)

**Comment by rom1504** [comment]
img2dataset has been run successful to download 5B samples in a week, this is done

last thing to do here: add info in the benchmark section of the readme

**Comment by mzolfaghari** [comment]
@rom1504 how much does it cost to store 200 TB of data on AWS? any suggestions for cheaper alternatives?

**Comment by rom1504** [comment]
@mzolfaghari it's indeed pretty costly to do that (thousands of dollar per months). We had the luck to have found funding for it!

Less expensive options include:
* downloading in a lower dimension : for example 256, reducing the size of the dataset to 100TB
* using aws glacier or the google cloud equivalent for long term storage
* buying disks

However keep in mind that the use of this dataset for training require hundred of GPUs which are much more costly than storage.
Other use cases will be better served by extracting subsets using the knn index.

We will provide more details when we release this dataset

**Comment by rom1504** [comment]
issue done
