### ISSUE TITLE
[laion high resolution] How to only extract a certain number of images?

### ISSUE THREAD

**Issue by jS5t3r** [rom1504/img2dataset#313]
This tutorial shows to download the whole dataset:

https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-high-resolution.md

I just want to download a certain number of images. E.g. 10k instead of all. 

Can I change that here? 

```
img2dataset --url_list laion-high-resolution --input_format "parquet"\
         --url_col "URL" --caption_col "TEXT" --output_format webdataset\
           --output_folder laion-high-resolution-output --processes_count 16 --thread_count 64 --image_size 1024\
            --resize_only_if_bigger=True --resize_mode="keep_ratio" --skip_reencode=True \
             --save_additional_columns '["similarity","hash","punsafe","pwatermark","LANGUAGE"]' --enable_wandb True
```

**Comment by rom1504** [comment]
Get the first metadata file and use pandas to extract only the first 10k
then run img2dataset on that

**Comment by rom1504** [comment]
save the file as parquet with pandas and give that to img2dataset

**Comment by jS5t3r** [comment]
Thanks. You can close this issue.
