### ISSUE TITLE
Cloudflare R2 Compatibility

### ISSUE THREAD

**Issue by zanussbaum** [rom1504/img2dataset#334]
To get Cloudflare R2 compatibility (which works out of the box with S3 APIs) for private buckets, I think we need to pass `acl=private` to many of the `fs` calls, such as `fs.open`, `fs.mkdir`, etc. Let me know if you would like a PR for this, I have some changes made on a fork and am testing that it works

**Comment by rom1504** [comment]
Pretty sure you can store settings in fsspec config file, see the readme

**Comment by zanussbaum** [comment]
Yes I saw that and was able to update the endpoint url as well as my credentials. Maybe I was doing it wrong but passing `'acl': 'private'` gave me errors when making a call to `fsspec.core.url_to_fs` which IIRC routed me to an error here: https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/session.py#L114
saying that there's no kwarg for `acl`

**Comment by rom1504** [comment]
ok, could you open an issue in fsspec repo and link to this issue ? let's try to figure it out with them
I think it would be nice if we can keep img2dataset agnostic to the file system kind

**Comment by rom1504** [comment]
looks like this was fixed upstream, let's update to the next release of fsspec when available

**Comment by zanussbaum** [comment]
lmk if there's anything i can do to help!

**Comment by rom1504** [comment]
this is fixed and released now
