### ISSUE TITLE
json not written and text file empty for files omitted from re-encoding

### ISSUE THREAD

**Issue by geroldmeisinger** [rom1504/img2dataset#344]
see `laion2B-en-aesthetics65.parquet` entry #29

```
wget http://www.pickthebrain.com/blog/wp-content/uploads/2015/10/Screen-Shot-2015-10-11-at-10.27.01-PM.png
magick identify Screen-Shot-2015-10-11-at-10.27.01-PM.png
Screen-Shot-2015-10-11-at-10.27.01-PM.png WEBP 854x532 854x532+0+0 8-bit sRGB 43088B 0.016u 0:00.005
```

docs:
"disable_all_reencoding if set to True, this will keep the image files in their original state with no resizing and no conversion, will not even check if the image is valid. Useful for benchmarks. To use only if you plan to post process the images by another program and you have plenty of storage available. (default False)"

using:
```
img2dataset ^
  --url_list "./laion2b-en-aesthetics65_100.csv" ^
  --input_format "csv" ^
  --output_folder laion2b-en-aesthetics65 ^
  --url_col "URL" ^
  --caption_col "TEXT" ^
  --output_format files ^
  --processes_count 8 ^
  --thread_count 24 ^
  --disable_all_reencoding True
```

(I exported the first 100 entries with ParquetViewer.exe to a .csv)

result:
renamed to: 000000029.jpg
empty: 000000029.txt
missing: 000000029.json

the text file is empty and there is no accompaning json file. is this the indented behaviour?

System is Windows 10

btw: Is there a way to resume this download using `--disable_all_reencoding False` to retry?

**Comment by rom1504** [comment]
I advise not using CSV, that's probably where the missing columns were
introduced

**Comment by geroldmeisinger** [comment]
Thanks for QUICK reposnse! It's not an issue with the csv. I just made this for to keep the issue simple and avoid starting a full download. The error originally occured with the parquet file.
