### ISSUE TITLE
How can I download directly to the original size without resizing?

### ISSUE THREAD

**Issue by TiaoziLiao** [rom1504/img2dataset#348]
How can I download directly to the original size without resizing?

**Comment by pabl0** [comment]
Have you tried  `--resize_mode=no`?
 
https://github.com/rom1504/img2dataset/blob/352ca4e1f530391f0a89f94eca5a6c36643eaafc/README.md?plain=1#L121

**Comment by rom1504** [comment]
That's right thanks @pabl0

**Comment by Leask** [comment]
The `--resize_mode=no` option is not functioning as expected.

Despite using this option, logs indicate resizing is still occurring:

`639it [20:04:18, 52.98s/it]worker - success: 0.598 - failed to download: 0.384 - failed to resize: 0.018 - images per sec: 10 - count: 10000`

This is perplexing, as resizing should not be happening when `resize_mode` is set to `no`.

**Comment by rom1504** [comment]
You can use disable_all_reencoding if you want to not re-encode and keep
broken images

**Comment by Leask** [comment]
1. I am still unclear why img2dataset resizes images even when `resize_mode = no` and `skip_reencode = True` are set.

2. Could you please clarify the difference between `disable_all_reencoding` and `skip_reencode`?

3. Can I use the `disable_all_reencoding` option ALONE to completely prevent any post-processing and obtain the original images, eliminating the need to control it via `skip_reencode` and `resize_mode`?

Thanks! 😄

**Comment by rom1504** [comment]
1 and 2 simply read the code of https://github.com/rom1504/img2dataset/blob/a70e10d352ec11fd611b86ab81a29223a16c841e/img2dataset/resizer.py

3. yes.

However do note if you get the original images without re-encoding it's most likely the result will not be useful because you will get any file including non-images.

The default of re-encoding and resizing is the right way to get image datasets for many reasons.

**Comment by Leask** [comment]
@rom1504 Thanks!
Your assistance with `disable_all_reencoding` was successful and met all requirements.
We use our own preprocessing functions and are therefore not concerned about some image failures.
Happy Holidays! 🎄
