### ISSUE TITLE
Is it possible to read LAION-400M from LAION-5B tarfiles?

### ISSUE THREAD

**Issue by xwen99** [rom1504/img2dataset#357]
Say that now I have access to tarfiles of LAION-5B (in webdataset format) stored in aws s3, metadata files of LAION-400M, and have a small local SSD (~ 1T). Is it possible to read out LAION-400M data directly (stored in link files or read online) for training without re-downloading, or what is the suggested practice?

**Comment by rom1504** [comment]
well you have 2 choices:

1. redownload laion400m. That will take a very short time so I recommend going that way
2. put in memory the text and url of laion400m (or a hash of them) and then read with webdataset directly from s3 all the laion5B dataset, and write samples in new tars (for example using webdataset tar writer) only if they are contained in laion400m. You will most likely need multiple machines to do this in a reasonable time

**Comment by xwen99** [comment]
Thanks for your prompt reply!
It's a pity that I am currently short of storage, so the 1st choice is not applicable now, and I'll see if I can implement the 2nd choice with reasonable computing, thanks!

**Comment by xwen99** [comment]
Well I would love to, but s3 is basically read-only for me haha...
