### ISSUE TITLE
How can I continue to download with incremental mode

### ISSUE THREAD

**Issue by Moonteresa** [rom1504/img2dataset#358]
My download interupted because of disk full, when I remove the exists files, and use --incremental to restart download, it seems began from the very beginning, can I creat some 1k ‘XXX.tar’ to pretend there are files? Or is there any way to solve the problem？ Thanks!

**Comment by pabl0** [comment]
Shards that have the `NNNNN_stats.json` file are finished and img2dataset does not attempt to redownload those shards again. If you migrate the actual data (.tar and .parquet files) somewhere else, keep the stats file and img2dataset will continue from where you left. Webdataset tarballs that are incomplete will need to be downloaded again. I don't believe there is an easy way to avoid that.

**Comment by rom1504** [comment]
That's correct
