### ISSUE TITLE
S3 laion5b upload faild 

### ISSUE THREAD

**Issue by kelisiya** [rom1504/img2dataset#359]
when I use `for i in {00000..00001}; do wget https://huggingface.co/datasets/laion/laion1B-nolang-joined/resolve/main/part-$i-4852663c-9585-44b0-9a45-f95c2b89c792-c000.snappy.parquet -O - | aws s3 cp - s3://laion5b/metadata/laion1B-nolang-joined/part-$i-4852663c-9585-44b0-9a45-f95c2b89c792-c000.snappy.parquet; done`

upload failed: - to s3://laion5b/metadata/laion1B-nolang-joined/part-00001-4852663c-9585-44b0-9a45-f95c2b89c792-c000.snappy.parquet An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist

**Comment by rom1504** [comment]
Hello,
This command is to *upload* to s3.
If you want to do that you need to create the right bucket and use that.
You can also download the files locally with another command provided in
the doc.
