### ISSUE TITLE
70% of files are not downloaded due to name resolution error

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [rom1504/img2dataset#360]
Hi, first of all thanks for providing such an amazing tool to the community

I am trying to perform a download of cc12m with the following command
```
img2dataset --url_list cc12m_shuffled.tsv --input_format "tsv"\
         --url_col "url" --caption_col "caption" --output-format webdataset --resize_mode keep_ratio \
           --output_folder cc12m --processes_count 11 --thread_count 512 --image_size 512\
             --enable_wandb True
```
In the results i.e stats json file, I see a whopping 7000 files (out of 10000) are errored  out from Tempoprary failure in name resolution error. How can I fix this. I am trying to run the script from my laptop ( How do I fix this issue, this could most likely be because of a dns related issue, I have not configured knot or bind9 resolver, could that be a potential source of issue ?

**Comment by rom1504** [comment]
Yes this is due to your DNS resolver being too slow. Try out knot resolver
