### ISSUE TITLE
Functionality to split a WDS

### ISSUE THREAD

**Issue by floschne** [rom1504/img2dataset#364]
Hi and first of all thanks for this amazing work!

In my scenario I have downloaded a small (500K) text-image pair dataset in form of a WDS stored it on an external storage container that I can mount in my system, i.e., I use a local path to instantiate the WDS.

My question now is, if there is a way to split the WDS into train, test, and validation without "manual extract/move/compress" work?

Thanks in advance!

**Comment by rom1504** [comment]
You can either split before downloading

filter at training time

or use the tar api from python ; or the webdataset helpers to extract the required splits
