### ISSUE TITLE
100% "hash mismatch" when doing md5 sanity check on laion2B

### ISSUE THREAD

**Issue by fabiozappo** [rom1504/img2dataset#366]
Hi, thank you for the amazing work behind this super fast repo!

I've been using this repo since quite some time but this time I wanted to apply a sanity check on the subset of laion2B that I am interested to download. 

To replicate the issue we can just use this parquet file: https://huggingface.co/datasets/laion/laion2b-en-vit-h-14-embeddings/blob/main/metadata/metadata_0000.parquet

I am using the latest release available (1.42.0)

Following [this](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion5B.md#with-md5-hashes-in-addition), I've tried to run the following command

```console
 img2dataset --input_format parquet --output_folder ./prova --url_col url --caption_col caption --url_list /path/to/my/file.parquet --processes_count 4 --image_size 256 --verify_hash '["md5", "md5"]' --compute_hash md5
```

But the results is a 0.0% Success and 100% fails.

![image](https://github.com/rom1504/img2dataset/assets/46443190/799fe9ab-db9b-4c0f-b3ad-5fef9e8fdd1f)

If I check the report I can see that the error "hash mismatch" occurred for every image.

Can you point me out what I am doing wrong?

**Comment by rom1504** [comment]
Did you get these files
https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion5B.md#with-md5-hashes-in-addition
?

**Comment by fabiozappo** [comment]
Thanks for the quick answer, I was actually not using those files but a different version. 

This works (success rate around 0.52):
``` <bash>
wget https://huggingface.co/datasets/laion/laion2B-en-md5/resolve/main/part-00000-0ff44bcb-73eb-4d29-b711-e46bfc1ad114-c000.snappy.parquet?download=true -O 0000.parquet
img2dataset --input_format parquet --url_col url --caption_col caption --url_list 0000.parquet --verify_hash '["md5", "md5"]' --compute_hash md5
```
This doesn't work (success rate 0.0):
``` <bash>
wget https://huggingface.co/datasets/laion/laion2b-en-vit-h-14-embeddings/resolve/main/metadata/metadata_0000.parquet?download=true -O 0000.parquet
img2dataset --input_format parquet --url_col url --caption_col caption --url_list 0000.parquet --verify_hash '["md5", "md5"]' --compute_hash md5
```

I don't understand why. Both the parquet file contain an "md5" column, then why for one is working and the other no?

I need to use the h14 laion2b-en-vit-h-14-embeddings because I am using the corresponding h14 image embeddings
