### ISSUE TITLE
Run img2dataset on goolge cloud

### ISSUE THREAD

**Issue by zwzhu-d** [rom1504/img2dataset#375]
I'm running img2dataset to download Laion400M on Google Cloud. But it is flagged as dos attack.
See the info below.
```
We are notifying you that your project My First Project (id: cellular-unity-410221) has been suspended because it was committing denial of service (DoS) attacks.
```

If there any solution to downloading with cloud service? Thank you!

**Comment by rom1504** [comment]
You can maybe reduce the download rates or use more nodes

But ultimately it's on google cloud to decide what they consider is
acceptable. You can ask them maybe
