### ISSUE TITLE
cannot download laion-high-resolution 

### ISSUE THREAD

**Issue by Harper714** [rom1504/img2dataset#378]
I cannot download the parquet files, showing **Access to this dataset has been disabled** on hugging face.

**Comment by rom1504** [comment]
https://laion.ai/notes/laion-maintanence/ ; hopefully it'll be resolved soon but it's not easy

**Comment by Harper714** [comment]
i see， thanks

> https://laion.ai/notes/laion-maintanence/ ; hopefully it'll be resolved soon but it's not easy
