### ISSUE TITLE
LAION-Aesthetic Huggingface Error: Access to this resource is disabled.

### ISSUE THREAD

**Issue by haodong2000** [rom1504/img2dataset#379]
Hi, I am following `dataset_examples/laion-aesthetic.md` to download the LAION-Aesthetic dataset.

However, while downloading the `.snappy.parquet` files from huggingface links, I got the error: Access to this resource is disabled.

I also met with this error when I clicked one link (https://huggingface.co/datasets/laion/laion2B-en-aesthetic/resolve/main/part-00001-9230b837-b1e0-4254-8b88-ed2976e9cee9-c000.snappy.parquet) manually.

I am wondering why and desiring for solutions T_T 

Thanks in advance for any help!

**Comment by rom1504** [comment]
https://laion.ai/notes/laion-maintanence/ ; hopefully it'll be resolved soon but it's not easy
