### ISSUE TITLE
hide opencv warnings

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#38]

**Comment by Skylion007** [comment]
@rom1504 What are the contents of the opencv warnings?

**Comment by rom1504** [comment]
```
Corrupt JPEG data: premature end of data segment
libpng error: PNG input buffer is incomplete
libpng warning: Unknown iTXt compression type or method
libpng warning: Unknown iTXt compression type or method
libpng warning: Unknown iTXt compression type or method
```
for example

**Comment by rom1504** [comment]
I tried https://github.com/opencv/opencv/pull/11207#issuecomment-817179341 and it didn't work

would be nice to find a solution to hide these warnings though, they make the output very noisy

**Comment by AntreasAntoniou** [comment]
Did you find a way to resolve this? I am currently having a similar issue with  ```mmco: unref short failure```

**Comment by rom1504** [comment]
no I didn't, still looking for a solution about this

**Comment by AntreasAntoniou** [comment]
This is actually a hard one to crack, and it really shouldn't be.

**Comment by rom1504** [comment]
finally found a way, see how at https://github.com/rom1504/img2dataset/pull/128/files#diff-dc8dbc9308016ebecb0a5dbf5c56db5173c3d1a46687f165938e79817f6ac237R29
