### ISSUE TITLE
cc3m dataset

### ISSUE THREAD

**Issue by lv-0413** [rom1504/img2dataset#391]
cc3m dataset is failed to download, becuase many urls of the dataset are dead. I only 70% success ratio of download image. Could you please share me the cc3m dataset by drive? Thank you very much

**Comment by Tangyueming311** [comment]
I only 

> cc3m dataset is failed to download, becuase many urls of the dataset are dead. I only 70% success ratio of download image. Could you please share me the cc3m dataset by drive? Thank you very muchCC3M 数据集下载失败，因为数据集的许多 URL 都已失效。我只有70%的下载成功率。你能通过驱动器分享cc3m数据集吗？谢谢

I only 40% 😂, I'm puzzled why there are no readily available downloads of the cc3m dataset on the internet

**Comment by rom1504** [comment]
70% success rate seems correct. Try to setup knot resolver to increase it if you get below 70%

Urls based datasets have link rot and that is normal, the web is not immutable

https://huggingface.co/datasets/pixparse/cc3m-wds you can try using this though, not sure what's the success rate for it

**Comment by Tangyueming311** [comment]
> 70% success rate seems correct. Try to setup knot resolver to increase it if you get below 70%70%的成功率似乎是正确的。尝试设置结解析器以增加它，如果你低于 70%
> 
> Urls based datasets have link rot and that is normal, the web is not immutable基于 URL 的数据集有链接腐烂，这是正常的，网络不是不可变的
> 
> https://huggingface.co/datasets/pixparse/cc3m-wds you can try using this though, not sure what's the success rate for ithttps://huggingface.co/datasets/pixparse/cc3m-wds 您可以尝试使用它，但不确定它的成功率是多少

Thank u very much😘
