### ISSUE TITLE
GCS url_path either not recognized as directory or mangled glob

### ISSUE THREAD

**Issue by kafonek** [rom1504/img2dataset#405]
If I have a set of input parquet files in GCS like `gs://bucket/foo/0.parquet`, `gs://bucket/foo/1.parquet`, etc, then if I pass in `url_list='gs://bucket/foo'` I'll end up in a code path where `fs.isdir('bucket/foo')` returns False and it tries to read the directory blob as a Parquet file.

If I pass in `url_list='gs://bucket/foo/'` then the glob for files becomes `bucket/foo//*.parquet` and has no matches.

I believe a fix is to `rstrip('/')` url path before globbing.

Relevant code is around https://github.com/rom1504/img2dataset/blob/main/img2dataset/reader.py#L59

**Comment by rom1504** [comment]
Makes sense, can you try that change and then open a PR ?
