### ISSUE TITLE
min/max file size + width/height ratio requirements

### ISSUE THREAD

**Issue by borisdayma** [rom1504/img2dataset#41]
Would you handle things such as:
* min file size: so that we don't download images of low quality
* max file size: I sometimes see people checking Content-Length to prevent from DDOS attacks
* min/max image dimensions ratio such as 2:1 between width & height

Or do you consider this kind of filtering as a subsequent step?

**Comment by rom1504** [comment]
the problem with doing this kind of filtering here is that it will not play well with the current sharding structure.
This tool currently saves roughly 10k images per tar file
if we include harsher filtering here, there will be much smaller tar files, which is not amazing

I'm not against adding that kind of filtering as indeed it seems like it could be useful, but then I'd like to rethink how shards are saved. An option I'm thinking of could be to return the name of the save tar as well as the number of items in it in each worker, and then let some other worker continue writing in it.
Another option is to repack at the end but that's not friendly with space.

For the specific case of cah dataset where we already know all the image sizes in advance, I would definitely do this kind of filtering as a subsequence step with a script such as https://github.com/rom1504/cah-prepro/blob/main/deduplicate/compute_more_stats.py

**Comment by borisdayma** [comment]
I was actually thinking it would be similar to when we lose files sure to download issues.
I typically do a first test to see what is the actual size of each tar and adjust accordingly.

If a filter has a really large impact (like discarding half of pictures), it could be an issue but not necessarily. If images are shuffled and we have a large number in each, we just make the target twice bigger.
This is not perfect but may be good enough and avoids complex logic.

**Comment by rom1504** [comment]
yeah ok, I guess it can work as a first step, we can consider improvement to sharding output later on
if you want to implement these filters as new options, feel free
