### ISSUE TITLE
Test and then consider changing recommendation to use knot-resolver instead of bind

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#42]
https://www.knot-resolver.cz/
it was found it might be better than bind9 for this use case

**Comment by borisdayma** [comment]
I also used it and worked well with no complex setup

**Comment by rom1504** [comment]
https://knot-resolver.readthedocs.io/en/stable/quickstart-install.html

**Comment by rom1504** [comment]
indeed it's easy to install and works better than bind9, let's make it the default here

**Comment by rom1504** [comment]
install: 
```
wget https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb
sudo dpkg -i knot-resolver-release.deb
sudo apt update
sudo apt install -y knot-resolver
```

start:
```
sudo systemctl start kresd@1.service
```

**Comment by rvencu** [comment]
There is a conf file to play with. I'll share settings for the AWS node but they are not universal

**Comment by rvencu** [comment]
`
-- Default empty Knot DNS Resolver configuration in -*- lua -*-
-- Bind ports as privileged user (root) --
net = {'127.0.0.53', '::1'}
net.list()
-- Switch to unprivileged user --
user('knot-resolver','knot-resolver')
-- Unprivileged
cache.size = 10000*MB
trust_anchors.add_file('/usr/share/dns/root.key', 'readonly')
`

**Comment by rom1504** [comment]
done
