### ISSUE TITLE
does not work on the provided examples

### ISSUE THREAD

**Issue by viyjy** [rom1504/img2dataset#54]
<img width="1758" alt="Screen Shot 2021-09-24 at 10 52 26 AM" src="https://user-images.githubusercontent.com/20442927/134719275-c44d8a09-d55e-4031-8859-069517cbb6d4.png">

The command used is:
`img2dataset --url_list=myimglist.txt --output_folder=./images --thread_count=4 resize_mode=no`

**Comment by rom1504** [comment]
hi, the issue is you forgot the -- before resize_mode
it should be --resize_mode and not resize_mode

however the error could definitely be presented better to the user, I'll add a check

**Comment by viyjy** [comment]
thanks, it works.
