### ISSUE TITLE
partial/incremental support ?

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#6]
consider supporting incremental downloading, to continue a previous download

**Comment by rom1504** [comment]
https://github.com/robvanvolt/DALLE-datasets/blob/635830a1693ba369d01d82cc6d80bf1b517eeb29/general/cc12m.py#L34 is one way

unclear how to make this work well while having webdataset support
maybe listing files from tars is fast ?

**Comment by rom1504** [comment]
this is now partially done by allowing the user to reuse an existing folder

**Comment by rom1504** [comment]
I am not sure whether the join operation between the metadata parquet and the input should be done in this tool or done by the user.
All the information is now available.
Doing it efficiently requires pyspark or dask, which I'd like to not add as a dependencies, so it might at best be an optional feature.

**Comment by rom1504** [comment]
I will build a script for this that takes
1. input files
2. status parquet files

And that output parquet files by doing input - status parquet. An unique key will have to be provided by the user. It can be url+caption for example. This can be done with pyspark efficiently.

Then this can be used as input of the downloader.
This should probably be a separate function and script.

It may optionally be called from the download function.

**Comment by mckinziebrandon** [comment]
Any update on this @rom1504 ? I'd love to use it! I just processed about 50M examples from the liaon-400M dataset using the cah-prepro repository, and it crashed with this error: 
```
  File "/coreflow/venv/lib/python3.6/site-packages/img2dataset/logging_utils.py", line 21, in _keep_most_frequent
    self.counter = Counter(dict(self.counter.most_common(self.max_size / 2)))
  File "/coreflow/miniconda/envs/cf_env/lib/python3.6/collections/__init__.py", line 553, in most_common
    return _heapq.nlargest(n, self.items(), key=_itemgetter(1))
  File "/coreflow/miniconda/envs/cf_env/lib/python3.6/heapq.py", line 569, in nlargest
    result = [(key(elem), i, elem) for i, elem in zip(range(0, -n, -1), it)]
TypeError: 'float' object cannot be interpreted as an integer
```
Not entirely sure the best way to "continue" as-is.

**Comment by rom1504** [comment]
Thanks for reporting.
I will share a script to continue with only what's left and will fix that bug in a few hours.

**Comment by mckinziebrandon** [comment]
Wow, thanks for the quick response. I was about to look into it but I'll hold off then. Thanks so much 🙏

**Comment by rom1504** [comment]
ok I fixed the bug you encountered

to continue, 
First delete your last tar if there is no corresponding .parquet file (might happen if it crashed)

you can run this to get a new "only what is left" input metadata:

Then pip install pyspark and run this (adapt the paths)
```
from pyspark.sql import SparkSession
from pyspark.sql.functions import rand
from glob import glob
spark = SparkSession.builder.config("spark.driver.memory", "16G") .master("local[16]").appName('spark-stats').getOrCreate()
metadata = spark.read.parquet("laion400m-metadata")
done = spark.read.parquet(*glob("your/output/*.parquet"))
not_done = metadata.join(done, on=(first_half['URL'] == done['url']) & (first_half['TEXT'] == done['caption']), how='left_anti')
not_done = not_done.orderBy(rand())
not_done.repartition(64).write.mode("overwrite").parquet("new_metadata_input")
```

What it does is 
1. read the initial metadata
2. read your current output
3. do a left join to keep only what's not done
4. order by rand to shuffle again (it can be important for this dataset to be shuffled for downstream use)
5. write back to a new folder

then you can use new_metadata_input as new input of img2dataset to continue, and you can use the same output folder, it will create tars+parquets following what you have 


I will find/build a more generic solution in the future, but for your use case that should work (that's what I did to download laion400m in several parts)

**Comment by mckinziebrandon** [comment]
Awesome, much appreciated. I'll try this out and let you know if I encounter any issues.

**Comment by heurainbow** [comment]
Some questions about incremental support that related to lation-400m:
1. it has 32 meta files, how does img2dataset name/order the output tar files?
2. I only use 2 meta files(say metaA and metaB), how can I know img2dataset has finished metaA? whether metaA is completed? what are the missing files failed to be downloaded?
3. how can I resume or retry metaA and metaB at the same location?

I found if I use ctrl+C to stop img2dataset command and rerun the same command, the number of tar files increase progressingly. I wonder if this is a new downloading or incremental downloading that skips un-done tar files.

My wandb logging status shows I only get a 35% success rate. Is this normal? How can I get higher success rate?

**Comment by rom1504** [comment]
> it has 32 meta files, how does img2dataset name/order the output tar files?

img2dataset read one file at a time, each file is then split in shards of size indicated in the command line (10k by default), these files are then saved in parallel. the initial order is kept.

> I only use 2 meta files(say metaA and metaB), how can I know img2dataset has finished metaA? whether metaA is completed? what are the missing files failed to be downloaded?

you can use the parquet files saved along side the tar files to know what was download. For example you can use the above script to remove the already downloaded samples from the initial collection

> how can I resume or retry metaA and metaB at the same location?

you can just do that, by default img2dataset will simply increment over the id of the last saved shard

> Say I already downloaded tar files by metaA and metaB, what happens if I add metaC in the meta dir together with metaA and metaB and rerun the same download command? And what's the tar file numbering if I download metaC in a different dir?

it will redownload metaA, metaB and then metaC, if you only want to download metaC you need to put only that
if you download in a different folder, it will start the numbering from 0 

> I found if I use ctrl+C to stop img2dataset command and rerun the same command, the number of tar files increase progressingly. I wonder if this is a new downloading or incremental downloading that skips un-done tar files.

it's a new download. If you want to do incremental downloading, you need to filter your input with what was already download with the script above

> My wandb logging status shows I only get a 35% success rate. Is this normal? How can I get higher success rate?

for laion400m that is not normal at all. I had a 98% success rate when downloading it.
You can check the error status in the wandb log. If I had to bet, I would think it's a dns issue, you can find some notes in the readme to improve on that

**Comment by heurainbow** [comment]
Thanks for your reply. 

Right now, I guess I expect the download behavior is 
if I use the same cmd at the same location:
1. it will auto detect tar files that not done/not started/finished;
2. for those not done, try to crawl and append to the exact same tar file;
3. for those finished, direct skip;
4. for those not started, create new tar files;
5. throught the whole process, the tar file numbering keeps the same, and the total number keeps the same.

To me, these features are very useful and important, especially for seperating whole laion-400m to multiple jobs. Say, I have a SSD disk downloading metaA and not finished, I can pass it to my team member to continue without any additional configure.

**Comment by rom1504** [comment]
Yes being in china is likely your issue regarding that error rate. I advise you rent a server outside of china to download the dataset then transfer the output back to you (through SCP/rsync/...)

For the incremental feature you expect I understand the convenience this would be, however that is not easy to implement efficiently for a large input collection. Currently you can achieve that by doing the join (described above) right before running img2dataset, but I didn't include it by default yet.

I will try to think of ways to implement that incremental feature efficiently in the future.

**Comment by heurainbow** [comment]
Any plans on option for 2?

**Comment by rom1504** [comment]
coming back to this
my first solution based on regenerating the input file with an antijoin is still valid

however I think now with the new architecture of the code, another solution could be to:
1. somehow save somewhere the last sample number downloaded (maybe in the stats files)
2. make the reader module here, able to skip directly to this sample number

should be possible but should be well tested because there are many edge cases to handle

**Comment by rom1504** [comment]
assuming the number of sample per shard is not changed during a run (reasonable assumption), the offset is actually directly computable by checking what is the last shard that was saved
combined with something that deletes all the incomplete shards at the beginning of a run, it could be a good solution for continuing

**Comment by rom1504** [comment]
this would work for an ordered collection of input files that do not change
it doesn't work for an input dataset that is reshuffled between runs. That can only works with the antijoin solution presented above.

So assuming that continuing solution is provided, it should be documented properly in the readme to let the users understand what is being done and what are the assumptions.

**Comment by thuangb** [comment]
So now what is the download behaviour if I resume a new download to the same folder after the old download crash ? Does it replace the old downloaded tar files ?

**Comment by rom1504** [comment]
this is still not implemented, if you restart in the same folder it will restart from the beginning and add more tars in the output folder

for now at least, you need to remove from the input collection what has already been done, for example with https://github.com/rom1504/img2dataset/issues/6#issuecomment-918524267

**Comment by thuangb** [comment]
> this is still not implemented, if you restart in the same folder it will restart from the beginning and add more tars in the output folder
> 
> for now at least, you need to remove from the input collection what has already been done, for example with [#6 (comment)](https://github.com/rom1504/img2dataset/issues/6#issuecomment-918524267)

I think you should include  [#6 (comment)](https://github.com/rom1504/img2dataset/issues/6#issuecomment-918524267) to README to make it more clear to the users. Because downloading LAION400M crashes a lot

**Comment by rom1504** [comment]
yeah I can do that

> downloading LAION400M crashes a lot

that is not normal. I downloaded it with no crash (and even a 10x bigger dataset)
feel free to open issues with the errors from crashes

**Comment by thuangb** [comment]
> yeah I can do that
> 
> > downloading LAION400M crashes a lot
> 
> that is not normal. I downloaded it with no crash (and even a 10x bigger dataset) feel free to open issues with the errors from crashes

The error is so random but most of the time it gives "OSError: Corrupt snappy compressed data"

**Comment by rom1504** [comment]
This is now done, see https://github.com/rom1504/img2dataset#incremental-mode
