### ISSUE TITLE
Add checksum of image

### ISSUE THREAD

**Issue by borisdayma** [rom1504/img2dataset#64]
I think it could be useful to add a checksum in the parquet files since we're downloading the images anyway and it's fast to compute.
It would help us do a real deduplication, not only on urls but on actual image content.

**Comment by rom1504** [comment]
yeah I agree that would be nice

**Comment by borisdayma** [comment]
What would you use? SHA256?

**Comment by rom1504** [comment]
yeah or MD5
it would be interesting to do a benchmark to check that it's indeed fast enough

**Comment by Skylion007** [comment]
MD5 is definitely fast enough. I've never been limited by the speed of an
MD5 implementation.

**Comment by rom1504** [comment]
fast enough here would be something like 20000 image/s to avoid slowing down the tool. Let's check whether that's true

**Comment by HaithemH** [comment]
Be aware that SHA256 is difficult to handle than MD5 because of its size. SHA256 is less secure than MD5 and that MD5 is faster than SHA256

**Comment by rom1504** [comment]
done
