### ISSUE TITLE
How generate parquet from WAT CC Files?

### ISSUE THREAD

**Issue by gjtjx** [rom1504/img2dataset#66]
RT
It there a tool to generate parquets from WAT CC Files Without Clip Filter?

**Comment by rom1504** [comment]
@rvencu will answer this one better than me
But to answer briefly yes such tools exist as part of the cah/laion project
Without clip filtering you'd be looking at something like 50B pairs of lower quality than laion400m
Do you have a particular objective in mind ?

**Comment by gjtjx** [comment]
Maybe10B High quality Image pairs, then the Gpus and Power is the limit. could you share this tool?

**Comment by rom1504** [comment]
That 10B clip filtered dataset is in progress of being built by some folks at laion/dalle pytorch discord. I advise you join there if you're interested to participate. https://discord.gg/xBPBXfcFHd
We're currently at 1.6B pairs

<https://github.com/rvencu/crawlingathome-gpu-hcloud> has some of the code

However I am curious on how you plan to use so many billions of pairs :) what is your plan?

**Comment by gjtjx** [comment]
Thank you,  we will use this data to do some Generate Models like DALLE
