### ISSUE TITLE
Stuck while downloading laion

### ISSUE THREAD

**Issue by hagiss** [rom1504/img2dataset#77]
I tried to download laion-400m using example command, but I stuck and got the log below.
![image](https://user-images.githubusercontent.com/66506438/147639827-6c622f52-9f7f-46c7-893f-3eb154b34f51.png)

How can I solve this problem?

**Comment by rom1504** [comment]
Do you have enough ram on this machine (I'd say 16GB is a minimum) ?

**Comment by hagiss** [comment]
Yes, my machine have 128GB ram memory.

Now, it works well. I think the problem was some packages in docker image.
Changing the docker image to another solved the problem.

Thank you!
